allowBuilds:
  '@parcel/watcher': true
  '@scu-plus/zhjw-captcha-ocr@github:meteor-liu-xinyu/zhjw-captcha-ocr': true
  '@swc/core': true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
  sharp: true
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@scu-plus/zhjw-captcha-ocr@github:meteor-liu-xinyu/zhjw-captcha-ocr'
  - '@swc/core'
  - esbuild
  - lmdb
  - msgpackr-extract
  - sharp
