allowBuilds:
  '@parcel/watcher': true
  '@scu-plus/zhjw-captcha-ocr@git+https://github.com/meteor-liu-xinyu/zhjw-captcha-ocr.git#bcddfde6a4a9d5edf8ebd3881bbdbc51417d338a': true
  '@swc/core': true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
  sharp: true
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - esbuild
  - lmdb
  - msgpackr-extract
  - sharp
